from turtle import circle, forward, left, pendown, penup, right, exitonclick, speed
#Program na hru piškvorky. Měl by splňovat funkčnost pro korektní vstupy, libovolná velikost pole.
#Strana ctverce
a=30
print("Ahoj právě si otevřel piškvorky")
j= input("Zadej jmeno prvniho hrace: ")
k= input("Zadej jmeno druheho hrace: ")
print ("V tomto duelu proti sobe nastoupí ", j ,"a ", k ,".")
#zvolime si velikost hraciho pole
x=int(input("Zadej počet sloupcu "))
y=int(input("Zadej počet řádků "))
print("Tato hra piskvorek je v poli ",x,"x",y)
nasobek=int(x * y)
#Vykreslení hracího pole (síťe)
for _ in range(y):
	for _ in range(x):
		for _ in range(4):
			forward(a)
			left(90)
		forward(a)
	left(180)
	forward(x*a)
	right(90)
	forward(a)
	right(90)
#Teď přijde na řadu cyklus, která proběhne pokud je počet všech polí sudý
if (nasobek%2==0):
	opakovani=int((nasobek)/2)	
	for f in range(opakovani):
#Vykreslení křížku
		print(" Ted je na řadě hráč ",k,)
		radka= int(input("Zadej řádku "))
		sloupec= int(input("Zadej sloupec "))
		penup()
		forward(sloupec * a - a)
		right(90)
		forward(radka * a - a)
		left(90)
		right(45)
		forward(4)
		pendown()
		forward(38)
		right(180)
		forward(19)
		right(90)
		forward(19)
		right(180)
		penup()
		forward(19)
		pendown()
		forward(19)
		right(180)
		penup()
		forward(19)
		left(90)
		forward(23)
		right(135)
		pendown()
		left(180)
		penup()
		forward(sloupec * a - a)
		right(180)
		left(90)
		forward(radka * a - a)
		right(90)
#Vykreslení kolečka
		print("Teď je na řadě hráč ",j,)
		radka= int(input("Zadej řádku "))
		sloupec= int(input("Zadej sloupec "))
		penup()
		forward(sloupec * a - 26)
		right(90)
		forward(radka * a - 15)
		pendown()
		circle(11)
		penup()
		right(90)
		forward(sloupec * a - 26)
		right(90)
		forward(radka * a - 15)
		right(90)
		pendown()
#Teď přijde na řadu cyklus, která proběhne pokud je počet všech polí lichý
else:
	opakovani=int((nasobek-1)/2)
	for f in range(opakovani):
#Vykreslení křížku
		print(" Ted je na řadě hráč ",k,)
		radka= int(input("Zadej řádku "))
		sloupec= int(input("Zadej sloupec "))
		penup()
		forward(sloupec * a - a)
		right(90)
		forward(radka * a - a)
		left(90)
		right(45)
		forward(4)
		pendown()
		forward(38)
		right(180)
		forward(19)
		right(90)
		forward(19)
		right(180)
		penup()
		forward(19)
		pendown()
		forward(19)
		right(180)
		penup()
		forward(19)
		left(90)
		forward(23)
		right(135)
		pendown()
		left(180)
		penup()
		forward(sloupec * a - a)
		right(180)
		left(90)
		forward(radka * a - a)
		right(90)
#Vykreslení kolečka
		print("Teď je na řadě hráč ",j,)
		radka= int(input("Zadej řádku "))
		sloupec= int(input("Zadej sloupec "))
		penup()
		forward(sloupec * a - 26)
		right(90)
		forward(radka * a - 15)
		pendown()
		circle(11)
		penup()
		right(90)
		forward(sloupec * a - 26)
		right(90)
		forward(radka * a - 15)
		right(90)
		pendown()
	#Vykreslení křížku (Jeden tah navíc prvního hráče jelikož je počet tahů lichý)
	print(" Ted je na řadě hráč ",k,)
	radka= int(input("Zadej řádku "))
	sloupec= int(input("Zadej sloupec "))
	penup()
	forward(sloupec * a - a)
	right(90)
	forward(radka * a - a)
	left(90)
	right(45)
	forward(4)
	pendown()
	forward(38)
	right(180)
	forward(19)
	right(90)
	forward(19)
	right(180)
	penup()
	forward(19)
	pendown()
	forward(19)
	right(180)
	penup()
	forward(19)
	left(90)
	forward(23)
	right(135)
	pendown()
	left(180)
	penup()
	forward(sloupec * a - a)
	right(180)
	left(90)
	forward(radka * a - a)
	right(90)
print("Konec hry")
exitonclick()